---
title: "Homwework_5"
author: "Laura_Calvimontes"
date: "2024-11-13"
output: html_document
---
```{r setup, include=TRUE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```


```{r Load_Packages-libraries, include=FALSE}
library(knitr)
library(ggplot2)
library(ggthemes)
library(dbplyr)
library(tidyverse)
library(tidyr)
library(broom)
library(purrr)
```

Cleaning data 
```{r Q1 Reding Homicide data}
url <- paste0("https://raw.githubusercontent.com/washingtonpost/",
              "data-homicides/refs/heads/master/homicide-data.csv")

homicides <- read_csv(file = url)
head(homicides, n = 5)

#mutate a new column
homicides_2 <- homicides %>% 
  mutate(city_name = paste(city, state, sep=", ") ) %>% 
  mutate(reported_date = ymd(reported_date)) %>% 
  mutate(total_hom = if_else(disposition == "Closed without arrest"| disposition == "Closed by arrest", TRUE, FALSE))
homicides_2

```

```{r baltimore}

baltimore <- homicides_2 %>% 
              filter(city == "Baltimore") %>% 
              mutate(reported_month = month(reported_date)) %>% 
              mutate(temperature =ifelse(reported_month %in% c(11,12,1,2,3,4), "Winter", "Summer")) %>% 
              mutate(year_month = format(reported_date, "%Y-%m")) %>% 
              mutate(year_month = as.factor(year_month)) %>% 
              group_by(year_month, temperature) %>%
              nest()
baltimore

arrest <- as.Date("2015-04-30")
```
```{r}

```


```{r}
baltimore_time <- ggplot(baltimore, aes(x = reported_date, fill = temperature))+
  geom_histogram (bins=108) +
  #geom_freqpoly(aes(x= reported_date, stat = "bin", color = "blue"))+
  ggtitle("Homicides in Baltimore, MD") +
  scale_fill_manual(values = c("Summer" = "gray", "Winter" = "skyblue"))+
  theme_grey()+
  theme(legend.position = "bottom",
        legend.title = element_blank())+
  geom_vline(xintercept = arrest, linetype="dashed", color = "red", size= 0.5)+
   geom_text(aes(x = arrest, y = 50, label = "Arrest of Freddie Carlos Grey"),
    color = "black", size = 2.5)
  
baltimore_time 
  
```
```{r}
baltimore_time <- ggplot(baltimore, aes(x = reported_date, fill = temperature))+
  geom_col(stat="identity") + geom_smooth(aes(group=1),method = "lm", se= F)+
  #geom_freqpoly(aes(x= reported_date, stat = "bin", color = "blue"))+
  ggtitle("Homicides in Baltimore, MD") +
  scale_fill_manual(values = c("Summer" = "gray", "Winter" = "skyblue"))+
  theme_grey()+
  theme(legend.position = "bottom",
        legend.title = element_blank())+
  geom_vline(xintercept = arrest, linetype="dashed", color = "red", size= 0.5)+
   geom_text(aes(x = arrest, y = 50, label = "Arrest of Freddie Carlos Grey"),
    color = "black", size = 2.5)
  
baltimore_time 
  
```

```{r}
baltimore2 <- homicides_2 %>% 
              filter(city == "Baltimore") %>% 
              mutate(year_month = format(reported_date, "%Y-%m")) %>% 
              mutate(reported_month = month(reported_date)) %>% 
              mutate(temperature =ifelse(reported_month %in% c(11,12,1,2,3,4), "Winter", "Summer")) %>% 
              mutate(year_month = as.factor(year_month)) %>% 
              group_by(year_month , temperature) %>% 
              summarize(month_homicides = n()) %>% 
              ungroup()

arrest <- as.Date("2015-04-30")

```

```{r}
str(baltimore2)
baltimote_plot2 <- ggplot(baltimore2, aes(x = year_month, y = month_homicides)) +
  geom_bar(stat = "identity", fill=temperature) + geom_smooth(method = "loess")
baltimote_plot2 
```

